name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ["Sync submodules to latest main"]  
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 判断逻辑
    if: |
      (github.event_name == 'push' && github.actor != 'github-actions[bot]') ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Clean install dependencies
      run: |
        rm -rf node_modules
        npm ci

    - name: Build Docusaurus site
      run: npm run build

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Deploy to GitHub Pages
      run: USE_SSH=true npm run deploy